<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="5" passed="1" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2018-07-23T21:06:46Z" name="Default suite" finished-at="2018-07-23T21:06:46Z" duration-ms="89">
    <groups>
    </groups>
    <test started-at="2018-07-23T21:06:46Z" name="Default test" finished-at="2018-07-23T21:06:46Z" duration-ms="89">
      <class name="by.htp.testng.TestDataProviderExample">
        <test-method is-config="true" signature="initSendLetterExpectedData()[pri:0, instance:by.htp.testng.TestDataProviderExample@c86b9e3]" started-at="2018-07-23T21:06:46Z" name="initSendLetterExpectedData" finished-at="2018-07-23T21:06:46Z" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initSendLetterExpectedData -->
        <test-method signature="testSendLetter(by.htp.entity.Letter)[pri:0, instance:by.htp.testng.TestDataProviderExample@c86b9e3]" started-at="2018-07-23T21:06:46Z" name="testSendLetter" data-provider="letters" finished-at="2018-07-23T21:06:46Z" duration-ms="15" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Letter [address=1@mail.ru, subject=subject1, content=text1]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSendLetter -->
        <test-method is-config="true" signature="initSendLetterExpectedData()[pri:0, instance:by.htp.testng.TestDataProviderExample@c86b9e3]" started-at="2018-07-23T21:06:46Z" name="initSendLetterExpectedData" finished-at="2018-07-23T21:06:46Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initSendLetterExpectedData -->
        <test-method signature="testSendLetter(by.htp.entity.Letter)[pri:0, instance:by.htp.testng.TestDataProviderExample@c86b9e3]" started-at="2018-07-23T21:06:46Z" name="testSendLetter" data-provider="letters" finished-at="2018-07-23T21:06:46Z" duration-ms="3" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Letter [address=2@mail.ru, subject=subject2, content=text2]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Letter [address=1@mail.ru, subject=subject1, content=text1]] but found [Letter [address=2@mail.ru, subject=subject2, content=text2]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Letter [address=1@mail.ru, subject=subject1, content=text1]] but found [Letter [address=2@mail.ru, subject=subject2, content=text2]]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at by.htp.testng.TestDataProviderExample.testSendLetter(TestDataProviderExample.java:64)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSendLetter -->
        <test-method is-config="true" signature="initSendLetterExpectedData()[pri:0, instance:by.htp.testng.TestDataProviderExample@c86b9e3]" started-at="2018-07-23T21:06:46Z" name="initSendLetterExpectedData" finished-at="2018-07-23T21:06:46Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initSendLetterExpectedData -->
        <test-method signature="testSendLetter(by.htp.entity.Letter)[pri:0, instance:by.htp.testng.TestDataProviderExample@c86b9e3]" started-at="2018-07-23T21:06:46Z" name="testSendLetter" data-provider="letters" finished-at="2018-07-23T21:06:46Z" duration-ms="11" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Letter [address=3@mail.ru, subject=subject3, content=text3]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Letter [address=1@mail.ru, subject=subject1, content=text1]] but found [Letter [address=3@mail.ru, subject=subject3, content=text3]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Letter [address=1@mail.ru, subject=subject1, content=text1]] but found [Letter [address=3@mail.ru, subject=subject3, content=text3]]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at by.htp.testng.TestDataProviderExample.testSendLetter(TestDataProviderExample.java:64)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSendLetter -->
      </class> <!-- by.htp.testng.TestDataProviderExample -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
